### ISSUE TITLE
 return ((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z'));

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-5#3]
https://github.com/EdikGres/Lab-work-5/blob/27eb2916bf5f89f23444aa0f3fdbdd6a818dd154/Lab-work-5/LibForLab.cpp#L31-L38

**Comment by marcfedorow** [comment]
Also `return ch |= ' ', ch >= 'a' && ch <= 'z';`

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
