### ISSUE TITLE
return;

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-5#7]
https://github.com/EdikGres/Lab-work-5/blob/2eab22b66e512481b578ddc571ba705f8e9596b9/Lab-work-5/LibForLab.cpp#L8

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.

**Comment by marcfedorow** [comment]
Closing unsolved issues is a misleading action: you do not let the other people know that yoir source code has any issues.

There is no reason to close issues that belong to repositories that are no more supported while they do not Interfere with your current work.
